feat:dynamic wallet selection
rsksmart/rsk-cli pull request #27
Opened 2024-11-28 17:43 UTC by SarveshLimaye

- Implemented dynamic wallet selection for executing CLI commands, enhancing flexibility and simplifying multi-wallet management.

- [x] Balance

![Screenshot 2024-11-28 at 11 06 32 PM](https://github.com/user-attachments/assets/a4196ad4-022d-4c72-ae26-bbf63e977ffd)

![Screenshot 2024-11-28 at 11 07 12 PM](https://github.com/user-attachments/assets/32b6b006-f973-41ec-a2a9-d1ae0a4b0e52)

- [x] Transfer 

![Screenshot 2024-11-28 at 11 10 01 PM](https://github.com/user-attachments/assets/f6c88cc0-5778-41c6-919f-d0618aa88bb7)

2024-11-29 16:27 UTC, ezequiel-rodriguez requested changes
Please, review the comments.  TY

2024-11-29 16:27 UTC, ezequiel-rodriguez commented on src/commands/balance.ts
> +            "⚠️ Wallet with the provided name does not exist. Using current wallet."
If the user did a typo, this assumption can transfer funds from an undesire wallet.   Best path here is to fail the tx and let the user review the command and try again

2024-11-29 16:27 UTC, ezequiel-rodriguez commented on src/commands/transfer.ts
> +            "⚠️ Wallet with the provided name does not exist. Using current wallet."
If the user did a typo, this assumption can transfer funds from an undesire wallet.   Best path here is to fail the tx and let the user review the command and try again

2024-11-29 16:27 UTC, ezequiel-rodriguez commented on src/utils/viemProvider.ts
> +            "⚠️ Wallet with the provided name does not exist. Using current wallet."
If the user did a typo, this assumption can transfer funds from an undesire wallet.   Best path here is to fail the tx and let the user review the command and try again

2024-11-30 05:00 UTC, SarveshLimaye commented
@ezequiel-rodriguez Thank you so much for the review. The suggestions above make total sense, and I’ve implemented all the changes recommended. Please let me know if any further changes are required.

2024-12-02 11:12 UTC, chrisarevalodev commented
LGTM

2024-12-03 01:23 UTC, ezequiel-rodriguez approved these changes
LGTM

2024-12-06 05:24 UTC, SarveshLimaye commented
Thanks for the review @ezequiel-rodriguez @chrisarevalodev

2024-12-13 22:12 UTC, ezequiel-rodriguez commented
Hey @SarveshLimaye, 
please submit your contribution in the following [form](https://forms.gle/aF9pFMfRyoygfzJWA) in order to get a reward for it.
Thank you

2025-01-10 09:29 UTC, chrisarevalodev commented
Hi @SarveshLimaye! In order to continue with the merge of your contribution we need you to merge your changes with the changes in the branch `pr-merge`. That's because there we have many PRs together and yours is the only one with conflicts. Please let us know if you need any help and as soon as you have this task done the reward will be distributed!

2025-01-11 17:57 UTC, SarveshLimaye commented
@chrisarevalodev Resolved all the conflicts.  I have merged all the changes from branch `pr-merge` into this branch. Pls do let me know if any further changes are required. 

Thank you !

2025-01-13 07:11 UTC, chrisarevalodev commented
LGTM @ezequiel-rodriguez

2025-01-23 17:44 UTC, ezequiel-rodriguez approved these changes
LGTM

2025-01-31 12:56 UTC, merged